version: '3'

services:
  xxl-mysql:
    image: ubuntu/mysql:8.0-20.04_beta
    container_name: xxl-mysql
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - "~/data/database/xxl-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: xxl
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password --max_connections=1000 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-time-zone='+8:00' --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --expire-logs-days=7
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    ports:
      - "8040:8080"
    environment:
      PARAMS: '
        --spring.datasource.url=jdbc:mysql://xxl-mysql:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        --spring.datasource.username=root
        --spring.datasource.password=123456
        --xxl.job.accessToken=DEFAULT_TOKEN'
    volumes:
      - ./logs:/data/applogs
                        